# Collision Filter Categories
CAT_WALL = 1
CAT_ROCK = 2
CAT_TOWER = 2
CAT_DRAGON_WALK = 3
CAT_DRAGON_FLY = 4
CAT_ANIMAL = 5
CAT_ARROW = 6
CAT_GROUND = 7

# Sprite Lists
SPRITE_LIST_STATIC = 'Static'
SPRITE_LIST_DYNAMIC = 'Dynamic'
